from setuptools import setup, find_packages

setup(
    name="voice-assistant-krishi",
    version="1.0.0",
    description="A virtual voice assistant like Google Assistant",
    packages=find_packages(),
    install_requires=[
        "speechrecognition==3.10.0",
        "pyttsx3==2.90",
        "pyaudio==0.2.11",
        "nltk==3.8.1",
        "spacy==3.7.2",
        "tensorflow==2.15.0",
        "numpy==1.24.3",
        "scipy==1.11.4",
        "requests==2.31.0",
        "python-dotenv==1.0.0",
        "pydub==0.25.1",
        "webrtcvad==2.0.10",
        "pvporcupine==3.0.0",
        "googletrans==4.0.0rc1",
        "pyautogui==0.9.54",
        "psutil==5.9.6",
        "playsound==1.3.0",
        "youtube-dl==2021.12.17",
        "spotipy==2.22.1",
        "twilio==8.10.0",
        "flask==3.0.0",
        "fastapi==0.104.1",
        "uvicorn==0.24.0"
    ],
    python_requires=">=3.8",
    author="Your Name",
    author_email="your.email@example.com",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Programming Language :: Python :: 3.13",
    ],
)